services:
  - type: web
    name: kpblog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog.settings
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_HOSTNAME}
    disk:
      name: media
      mountPath: static/media
      sizeGB: 1
