# Generated by Django 5.0.1 on 2024-02-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_auther_alter_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
